[theme]
base="dark"
primaryColor="#4ade80"
backgroundColor="#0b1220"
secondaryBackgroundColor="#111827"
textColor="#e5e7eb"
font="sans serif"

[server]
maxUploadSize = 200
headless = true


